(()=>{"use strict";
const all=window.TESIS_S8_QUESTIONS||[];let pool=[...all],idx=0,selected=null,answered=new Map();
const THEORY={
1:`<p><strong>Proceso de investigación.</strong> La investigación se desarrolla como una secuencia lógica: planeamiento, organización, implementación, ejecución, evaluación y comunicación de resultados. En el planeamiento se define qué se investigará, por qué, con qué fundamento y cómo se realizará; en la implementación se preparan instrumentos y recursos; en la ejecución se recolectan y analizan los datos; finalmente se evalúa y comunica lo encontrado.</p><p><strong>Clave metodológica:</strong> el instrumento, la muestra y el análisis no deben aparecer antes de definir problema, objetivos, variables y diseño. Cada decisión posterior depende de la anterior.</p>`,
2:`<p><strong>Problema de investigación.</strong> El problema parte de una dificultad, vacío o situación que requiere investigación. Debe pasar de una realidad amplia a una formulación concreta, delimitada y empíricamente abordable. La formulación debe expresar relación entre variables, escribirse como pregunta, permitir comprobación empírica y definir población, espacio y tiempo cuando corresponda.</p><p><strong>Clave metodológica:</strong> delimitar significa hacer manejable el problema: qué variables, en quiénes, dónde y en qué periodo se estudiarán.</p>`,
3:`<p><strong>Objetivos y justificación.</strong> Los objetivos expresan lo que se pretende lograr y deben ser claros, concretos, medibles y congruentes con el problema. El objetivo general representa el propósito central; los específicos lo descomponen en metas operativas. La justificación explica por qué vale la pena investigar y qué utilidad teórica, metodológica, práctica o social pueden tener los resultados.</p><p><strong>Clave metodológica:</strong> problema, objetivo e hipótesis deben referirse al mismo fenómeno y conservar coherencia entre sí.</p>`,
4:`<p><strong>Enfoque, tipo y diseño.</strong> El enfoque define la orientación general del estudio: cuantitativo, cualitativo o mixto. El diseño es la estructura utilizada para planificar, implementar y analizar la investigación. En estudios no experimentales el investigador observa sin manipular deliberadamente la exposición; pueden ser transversales o longitudinales. Entre los diseños analíticos destacan casos y controles y cohortes. En investigación experimental se consideran manipulación, grupo control y, en el experimento verdadero, aleatorización.</p><p><strong>Clave metodológica:</strong> casos y controles parte del desenlace y busca exposición previa; cohortes parte de la exposición y observa el desenlace. La existencia de una “intervención” en el título no convierte automáticamente al estudio en experimental: depende de quién asigna la exposición y cómo se forman los grupos.</p>`,
5:`<p><strong>Marco teórico y antecedentes.</strong> La revisión bibliográfica permite conocer qué se ha investigado, qué métodos se han utilizado, qué resultados se han encontrado y qué vacíos permanecen. Los antecedentes deben ser estudios previos comparables y relevantes; las bases teóricas desarrollan los conceptos necesarios para comprender las variables y el problema.</p><p><strong>Clave metodológica:</strong> una revisión de calidad no es una colección de citas. Debe seleccionar, organizar, comparar y sintetizar evidencia pertinente y reciente.</p>`,
6:`<p><strong>Hipótesis y variables.</strong> La hipótesis plantea una relación entre variables susceptible de comprobación. Sus elementos básicos incluyen unidad de estudio, variables y nexo lógico. Las variables requieren definición conceptual y operacional. Operacionalizar significa transformar conceptos en elementos medibles mediante dimensiones, indicadores, categorías y escalas de medición.</p><p><strong>Clave metodológica:</strong> una variable no está lista para recolectarse hasta que exista una regla clara y reproducible para medirla y clasificarla.</p>`,
7:`<p><strong>Recolección de datos.</strong> Recolectar datos equivale a medir variables de acuerdo con un plan. Debe precisarse qué se mide, cómo se mide, con qué instrumento, cómo se aplica y cómo se preparan los datos para el análisis. Los instrumentos deben buscar confiabilidad, validez y objetividad; cuando corresponde, se someten a prueba piloto y posteriormente los datos se codifican en una matriz.</p><p><strong>Clave metodológica:</strong> técnica e instrumento no son lo mismo. Por ejemplo, análisis documental es una técnica; una ficha de registro es el instrumento con el que se capturan los datos.</p>`
};
const $=id=>document.getElementById(id), letters=["A","B","C","D","E"];
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a}
function current(){return pool[idx]}
function stats(){const arr=[...answered.values()],done=arr.length,right=arr.filter(x=>x.correct).length;$("done").textContent=done;$("right").textContent=right;$("pct").textContent=done?Math.round(right*100/done)+"%":"0%";$("progressBar").style.width=(pool.length?((idx+1)/pool.length*100):0)+"%";$("total").textContent=pool.length;renderSummary()}
function renderSummary(){const box=$("classResults");box.innerHTML="";for(let c=1;c<=7;c++){const entries=[...answered.entries()].filter(([id])=>id.startsWith("C"+c+"Q")).map(([,v])=>v);const r=entries.filter(x=>x.correct).length;const d=entries.length;const el=document.createElement("div");el.innerHTML="Clase "+String(c).padStart(2,"0")+"<strong>"+r+"/"+d+"</strong>";box.appendChild(el)}$("summary").classList.toggle("show",answered.size>0)}
function render(){const q=current();if(!q){$("quizCard").innerHTML="<h2>No hay preguntas para este filtro.</h2>";return}selected=null;$("qClass").textContent="CLASE "+String(q.classNo).padStart(2,"0")+" · "+q.topic;$("qNum").textContent=(idx+1)+" / "+pool.length;$("stem").textContent=q.stem;const ops=$("options");ops.innerHTML="";q.options.forEach((o,i)=>{const b=document.createElement("button");b.className="option";b.innerHTML="<strong>"+letters[i]+".</strong> "+o;b.onclick=()=>{if(answered.has(q.id))return;selected=i;[...ops.children].forEach(x=>x.classList.remove("selected"));b.classList.add("selected")};ops.appendChild(b)});$("feedback").classList.remove("show");const prev=answered.get(q.id);if(prev){selected=prev.choice;showFeedback(q,prev.choice,true)}stats()}
function showFeedback(q,choice,restored=false){const children=[...$("options").children];children.forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add("correct");if(i===choice&&i!==q.answer)b.classList.add("wrong")});const ok=choice===q.answer;$("feedbackHead").textContent=ok?"Respuesta correcta":"Respuesta incorrecta";$("feedbackHead").className="feedback-head "+(ok?"ok":"bad");$("explanation").textContent=q.explanation;$("theoryText").innerHTML=THEORY[q.classNo]||"<p>Repasa el desarrollo teórico de esta clase.</p>";$("rationales").innerHTML=q.rationales.map((r,i)=>'<div class="rat"><strong>'+letters[i]+'. '+(i===q.answer?"Correcta":"")+'</strong> '+r+'</div>').join("");$("fija").innerHTML="<strong>BADBEAR.MED FIJA:</strong>"+q.fija;$("feedback").classList.add("show");if(!restored){answered.set(q.id,{choice,correct:ok});stats()}}
$("checkBtn").onclick=()=>{const q=current();if(selected===null||answered.has(q.id))return;showFeedback(q,selected)};
$("nextBtn").onclick=()=>{if(idx<pool.length-1){idx++;render()}};
$("prevBtn").onclick=()=>{if(idx>0){idx--;render()}};
$("shuffleBtn").onclick=()=>{pool=shuffle([...pool]);idx=0;render()};
$("resetBtn").onclick=()=>{answered.clear();idx=0;render()};
$("classFilter").onchange=e=>{const v=e.target.value;pool=v==="all"?[...all]:all.filter(q=>String(q.classNo)===v);idx=0;render()};
render();
})();