window.BADBEAR_TRAUMA_TEMAS = [
  {id:"clase-1",clase:1,titulo:"Historia clínica, fisiología ósea y semiología del aparato locomotor",area:"Bases",icono:"🩺",descripcion:"Anamnesis traumatológica, exploración funcional, rangos de movilidad, pruebas complementarias y bases de fisiología ósea."},
  {id:"clase-2",clase:2,titulo:"Generalidades de patología del aparato locomotor y complicaciones de las fracturas",area:"Fracturas",icono:"🦴",descripcion:"Principios de lesión musculoesquelética, consolidación y principales complicaciones locales y sistémicas de las fracturas."},
  {id:"clase-3",clase:3,titulo:"Fracturas y luxaciones del miembro superior",area:"Extremidad superior",icono:"💪",descripcion:"Abordaje de fracturas y luxaciones de hombro, brazo, codo, antebrazo, muñeca y mano, con enfoque clínico-radiológico."},
  {id:"clase-4",clase:4,titulo:"Fracturas y luxaciones del miembro inferior",area:"Extremidad inferior",icono:"🦵",descripcion:"Fracturas y luxaciones de cadera, fémur, rodilla, tibia, tobillo y pie; diagnóstico, clasificación y manejo inicial."},
  {id:"clase-5",clase:5,titulo:"Fracturas y lesiones del cartílago de crecimiento en niños",area:"Trauma pediátrico",icono:"👶",descripcion:"Lesiones fisarias y fracturas pediátricas, con énfasis en Salter-Harris, remodelación y complicaciones del crecimiento."},
  {id:"clase-6",clase:6,titulo:"Anomalías congénitas frecuentes del aparato locomotor",area:"Ortopedia pediátrica",icono:"🧩",descripcion:"Principales deformidades congénitas musculoesqueléticas, reconocimiento clínico y principios de tratamiento ortopédico."},
  {id:"clase-7",clase:7,titulo:"Patología de columna vertebral",area:"Columna",icono:"🦴",descripcion:"Patología traumática y ortopédica de columna, deformidades, síndromes clínicos y evaluación imagenológica básica."},
  {id:"clase-8",clase:8,titulo:"Manejo de las fracturas expuestas",area:"Urgencias",icono:"🚑",descripcion:"Evaluación inicial, clasificación de fracturas abiertas, antibióticos, desbridamiento, estabilización y prevención de infección."},
  {id:"clase-9",clase:9,titulo:"Infecciones del aparato locomotor",area:"Infecciones",icono:"🦠",descripcion:"Osteomielitis, artritis séptica, secuestro, involucro, espacio muerto óseo y principios de tratamiento médico-quirúrgico."},
  {id:"clase-10",clase:10,titulo:"Lesiones musculares y tendinosas",area:"Partes blandas",icono:"💥",descripcion:"Mecanismos de lesión muscular y tendinosa, diagnóstico clínico, imágenes y tratamiento conservador o quirúrgico."},
  {id:"clase-11",clase:11,titulo:"Lesiones meniscales y ligamentarias",area:"Rodilla",icono:"🦿",descripcion:"Lesiones meniscales, ligamentos cruzados y colaterales, pruebas clínicas, resonancia y criterios terapéuticos."},
  {id:"clase-12",clase:12,titulo:"Tumores óseos del aparato locomotor",area:"Oncología ortopédica",icono:"🔬",descripcion:"Enfoque radiológico de lesiones óseas, benignidad versus agresividad, tumores frecuentes y principios diagnósticos."},
  {id:"clase-13",clase:13,titulo:"Enfermedades inflamatorias y degenerativas",area:"Ortopedia",icono:"♿",descripcion:"Artropatías inflamatorias y degenerativas, cambios estructurales, clínica, imágenes y tratamiento ortopédico básico."},
  {id:"clase-14",clase:14,titulo:"Síndromes dolorosos del aparato locomotor",area:"Dolor musculoesquelético",icono:"⚡",descripcion:"Evaluación de síndromes dolorosos frecuentes, diagnóstico diferencial y enfoque funcional del aparato locomotor."},
  {id:"clase-15",clase:15,titulo:"Manejo del paciente politraumatizado",area:"Trauma",icono:"🚨",descripcion:"Priorización inicial, evaluación del paciente con trauma múltiple, lesiones musculoesqueléticas graves y coordinación del manejo definitivo."}
];
