window.BADBEAR_NEURO_TEMAS = [
  {id:"neuroanatomia",numero:"0",titulo:"Neuroanatomía clínica desde cero",area:"Bases",icono:"🧠",descripcion:"Curso propio BADBEAR.MED: organización del sistema nervioso, vías, médula, tronco, pares craneales, cerebelo, ganglios basales, corteza e irrigación con correlación clínica."},
  {id:"polineuropatias",numero:"1",titulo:"Polineuropatías",area:"Neuromuscular",icono:"🧵",descripcion:"Localización periférica, patrones axonales y desmielinizantes, Guillain-Barré, neuropatía diabética y estudio neurofisiológico."},
  {id:"parkinson",numero:"2",titulo:"Enfermedad de Parkinson",area:"Movimiento",icono:"🚶",descripcion:"Ganglios basales, síndrome parkinsoniano, clínica motora y no motora, diagnóstico diferencial y tratamiento."},
  {id:"epilepsias",numero:"3",titulo:"Epilepsias",area:"Epilepsia",icono:"⚡",descripcion:"Clasificación de crisis, síndromes epilépticos, diagnóstico electroclínico y tratamiento."},
  {id:"neurotuberculosis",numero:"4",titulo:"Neurotuberculosis",area:"Neuroinfecciones",icono:"🦠",descripcion:"Meningitis tuberculosa, tuberculomas, complicaciones vasculares, LCR, neuroimagen y tratamiento."},
  {id:"neurocisticercosis",numero:"5",titulo:"Neurocisticercosis",area:"Neuroinfecciones",icono:"🧫",descripcion:"Formas parenquimatosas y extraparenquimatosas, estadios radiológicos, diagnóstico y manejo."},
  {id:"miopatias",numero:"6",titulo:"Miopatías",area:"Neuromuscular",icono:"💪",descripcion:"Debilidad proximal, enzimas musculares, electromiografía, distrofias y enfoque diagnóstico."},
  {id:"infecciones-snc-sgb",numero:"7",titulo:"Infecciones del SNC - SGB",area:"Neuroinfecciones",icono:"🧬",descripcion:"Infecciones neurológicas y síndrome de Guillain-Barré con enfoque clínico, LCR y soporte crítico."},
  {id:"esclerosis-multiple",numero:"8",titulo:"Esclerosis múltiple",area:"Neuroinmunología",icono:"🛡️",descripcion:"Desmielinización del SNC, brotes, criterios diagnósticos, resonancia y tratamiento."},
  {id:"encefalitis-autoinmune",numero:"9",titulo:"Encefalitis autoinmune",area:"Neuroinmunología",icono:"🧠",descripcion:"Síndromes encefalíticos inmunomediados, anticuerpos, diagnóstico diferencial y tratamiento."},
  {id:"miastenia-gravis",numero:"10",titulo:"Miastenia gravis",area:"Neuromuscular",icono:"🔋",descripcion:"Unión neuromuscular, fatigabilidad, anticuerpos, electrofisiología, timo y crisis miasténica."},
  {id:"coma",numero:"11",titulo:"Coma",area:"Urgencias",icono:"🚨",descripcion:"Conciencia, formación reticular, exploración, patrones pupilares, causas y prioridades diagnósticas."},
  {id:"demencias",numero:"12",titulo:"Demencias",area:"Cognición",icono:"🧩",descripcion:"Deterioro cognitivo, Alzheimer, demencia vascular, cuerpos de Lewy y evaluación clínica."},
  {id:"cefaleas",numero:"13",titulo:"Cefaleas",area:"Cefaleas",icono:"🤕",descripcion:"Cefaleas primarias, secundarias, banderas rojas, migraña y algoritmos diagnósticos."},
  {id:"ela",numero:"14",titulo:"ELA",area:"Motoneurona",icono:"🧬",descripcion:"Esclerosis lateral amiotrófica, primera y segunda motoneurona, diagnóstico y manejo multidisciplinario."},
  {id:"segunda-neurona",numero:"15",titulo:"Patología de la segunda neurona",area:"Motoneurona",icono:"🦾",descripcion:"Síndromes de motoneurona inferior, localización, signos clínicos y diagnóstico diferencial."},
  {id:"infarto-cerebral",numero:"16",titulo:"Infarto cerebral",area:"Vascular",icono:"🩸",descripcion:"ACV isquémico, territorios arteriales, neuroimagen, evaluación aguda y prevención secundaria."},
  {id:"rescate-vascular",numero:"17",titulo:"Terapia de rescate vascular",area:"Vascular",icono:"⏱️",descripcion:"Reperfusión en ictus: selección, trombólisis, trombectomía y ventanas terapéuticas."},
  {id:"hemorragia-intracerebral",numero:"18",titulo:"Hemorragia intracerebral",area:"Vascular",icono:"🩸",descripcion:"Hemorragia espontánea, localización, neuroimagen, expansión, manejo y complicaciones."},
  {id:"neuroimagenes-infecciosas",numero:"19",titulo:"Neuroimágenes en enfermedades infecciosas del SNC",area:"Neuroimagen",icono:"🖥️",descripcion:"Patrones tomográficos y por resonancia en infecciones del sistema nervioso central."},
  {id:"estado-epileptico",numero:"20",titulo:"Estado epiléptico",area:"Epilepsia",icono:"⚡",descripcion:"Definición operativa, estabilización, tratamiento escalonado y estado refractario."},
  {id:"neuroimagenes-vasculares",numero:"21",titulo:"Neuroimágenes en enfermedades vasculares del SNC",area:"Neuroimagen",icono:"🧠",descripcion:"TC, angio-TC, RM y patrones vasculares en isquemia y hemorragia cerebral."}
];