(() => {
"use strict";
window.BADBEAR_NEURO_CONTENIDOS=window.BADBEAR_NEURO_CONTENIDOS||{};
window.BADBEAR_NEURO_CONTENIDOS["coma"]=`
<section class="lesson-intro deep-intro"><span class="lesson-label">UNIDAD 11 · COMA</span><h2>Coma: fisiología de la conciencia, localización y estabilización del paciente no respondedor</h2><p>Desarrollo basado en <strong>“11. Coma - Seminario.pdf”</strong>. El material recorre ABC y escalas de alerta, Glasgow, semiología focal vs. difusa, pupilas, reflejos oculares, patrones respiratorios, comas estructurales, metabólicos y tóxicos.</p></section>
<section class="lesson-section"><div class="lesson-number">11.1</div><h2>Definición operativa</h2><p>El coma es un estado de ausencia de vigilia y de respuesta consciente sostenida. Su análisis exige separar dos componentes de la conciencia: <strong>arousal</strong> o nivel de activación y <strong>contenido</strong> de la conciencia. La lesión bilateral de hemisferios o del sistema reticular activador ascendente puede alterar profundamente el nivel de conciencia.</p></section>
<section class="lesson-section"><div class="lesson-number">11.2</div><h2>La prioridad no es diagnosticar: es estabilizar</h2><p>El PDF abre con ABC porque un paciente comatoso puede morir por hipoxia, hipoventilación, aspiración, shock o hipoglucemia antes de que se complete la localización neurológica.</p><div class="mechanism-flow"><div><b>A</b><span>Vía aérea y protección cervical</span></div><i>→</i><div><b>B</b><span>Ventilación y oxigenación</span></div><i>→</i><div><b>C</b><span>Circulación y perfusión</span></div><i>→</i><div><b>Neurológico</b><span>Glucosa + Glasgow + pupilas</span></div></div></section>
<section class="lesson-section"><div class="lesson-number">11.3</div><h2>Escala de coma de Glasgow</h2><p>Glasgow objetiva respuesta ocular, verbal y motora. Es útil para seguimiento y comunicación entre equipos, pero no sustituye la exploración de pupilas, movimientos oculares, patrón respiratorio ni lateralización.</p><div class="bb-fija-neuro"><b>BADBEAR.MED FIJA:</b> Glasgow cuantifica <strong>respuesta</strong>; no establece por sí sola la etiología ni localiza la lesión.</div></section>
<section class="lesson-section"><div class="lesson-number">11.4</div><h2>Anamnesis: el tiempo de instalación es una prueba diagnóstica</h2><p>El material pide definir si el inicio fue brusco o progresivo, buscar cefalea o convulsiones previas, DM, HTA, alcohol, fármacos, tóxicos y traumatismo. Un coma súbito favorece causas vasculares, epilépticas, tóxicas o metabólicas abruptas; uno progresivo amplía el espectro a masas, infecciones, trastornos metabólicos y edema cerebral.</p></section>
<section class="lesson-section"><div class="lesson-number">11.5</div><h2>Focal vs. difuso</h2><p>La presencia de anisocoria, desviación conjugada de la mirada, hemiparesia o asimetría motora favorece lesión estructural focal. Un examen simétrico con pupilas reactivas en un contexto compatible puede favorecer causa metabólica o tóxica, aunque ninguna regla aislada es absoluta.</p></section>
<section class="lesson-section"><div class="lesson-number">11.6</div><h2>Pupilas: ventana al tronco encefálico</h2><p>El PDF dedica una sección al examen pupilar y a anisocoria/enclavamiento. Tamaño, simetría y reactividad aportan información sobre vías parasimpáticas y simpáticas y pueden advertir compresión de tronco o herniación.</p><div class="clinical-pearl"><b>Clave anatómica:</b> una pupila unilateral dilatada y poco reactiva en deterioro agudo obliga a pensar en compresión del III par y herniación uncal hasta demostrar otra causa.</div></section>
<section class="lesson-section"><div class="lesson-number">11.7</div><h2>Motilidad y reflejos oculares</h2><p>Los reflejos oculocefálicos y oculovestibulares evalúan integridad de circuitos del tronco encefálico en pacientes sin contraindicación cervical. La posición ocular espontánea y las respuestas reflejas pueden distinguir lesión hemisférica de lesión troncal o depresión metabólica profunda.</p></section>
<section class="lesson-section"><div class="lesson-number">11.8</div><h2>Patrones respiratorios</h2><p>El seminario incluye patrones respiratorios porque la respiración integra corteza, diencéfalo, puente y bulbo. Respiración periódica, hiperventilación neurogénica, respiración atáxica u otros patrones deben interpretarse junto con el resto de la exploración, nunca de forma aislada.</p></section>
<section class="lesson-section"><div class="lesson-number">11.9</div><h2>Respuesta motora y posturas</h2><p>La respuesta al estímulo nociceptivo permite reconocer localización asimétrica, retirar, localizar o identificar posturas patológicas. La diferencia entre flexión anormal, extensión y ausencia de respuesta tiene valor pronóstico y topográfico.</p></section>
<section class="lesson-section"><div class="lesson-number">11.10</div><h2>Comas estructurales</h2><p>Hemorragia, infarto extenso, masa, hidrocefalia, edema y herniación producen coma mediante daño directo de estructuras de conciencia o por desplazamiento/compresión secundaria. La neuroimagen urgente responde a una pregunta anatómica: <strong>¿hay una lesión que requiera intervención inmediata?</strong></p></section>
<section class="lesson-section"><div class="lesson-number">11.11</div><h2>Hipoglucemia</h2><p>El PDF describe hipoglucemia severa como causa reversible y tiempo-dependiente. El cerebro depende de suministro continuo de glucosa; la fase adrenérgica puede progresar a confusión, estupor y coma. La glucemia capilar debe obtenerse de inmediato.</p></section>
<section class="lesson-section"><div class="lesson-number">11.12</div><h2>Hiperglucemia extrema: CAD y estado hiperosmolar</h2><p>En cetoacidosis diabética domina acidosis metabólica con cetosis; en estado hiperosmolar, hiperglucemia y osmolaridad elevadas producen deshidratación celular. El deterioro de conciencia deriva de alteraciones metabólicas sistémicas y osmóticas.</p></section>
<section class="lesson-section"><div class="lesson-number">11.13</div><h2>Trastornos del sodio y calcio</h2><p>La hiponatremia aguda favorece entrada de agua a células cerebrales y edema; la hipernatremia extrae agua y contrae el parénquima. El material también destaca hipercalcemia severa como causa de deterioro neurológico por alteración de excitabilidad de membrana.</p></section>
<section class="lesson-section"><div class="lesson-number">11.14</div><h2>Encefalopatía urémica y hepática</h2><p>Ambas son causas de disfunción cerebral difusa. La anamnesis, contexto sistémico, laboratorio y ausencia de focalidad estructural concordante orientan. El tratamiento se dirige a la alteración metabólica subyacente.</p></section>
<section class="lesson-section"><div class="lesson-number">11.15</div><h2>Coma mixedematoso</h2><p>El seminario incluye hipotiroidismo extremo dentro de causas endocrinas. Hipotermia, bradicardia, hipoventilación, hiponatremia y deterioro progresivo de conciencia pueden coexistir.</p></section>
<section class="lesson-section"><div class="lesson-number">11.16</div><h2>Comas tóxicos</h2><div class="table-wrap-pro"><table><thead><tr><th>Tóxico</th><th>Pistas del material</th><th>Problema dominante</th></tr></thead><tbody><tr><td>Opioides</td><td>Miosis + depresión respiratoria</td><td>Hipoventilación</td></tr><tr><td>Benzodiacepinas/barbitúricos</td><td>Depresión del sensorio</td><td>Depresión SNC</td></tr><tr><td>Alcohol</td><td>Contexto clínico y tóxico</td><td>Depresión, hipoglucemia u otras asociaciones</td></tr><tr><td>CO</td><td>Exposición ambiental</td><td>Hipoxia tisular</td></tr><tr><td>Tricíclicos</td><td>Toxicidad neurológica y cardiovascular</td><td>Arritmias + convulsiones + coma</td></tr></tbody></table></div></section>
<section class="lesson-section"><div class="lesson-number">11.17</div><h2>Algoritmo profesional</h2><div class="decision-tree"><div class="decision-node primary"><b>ABC + glucosa</b><span>Corregir amenazas reversibles inmediatas</span></div><div class="decision-arrow">↓</div><div class="decision-node"><b>Glasgow + pupilas</b><span>Cuantificar y buscar herniación</span></div><div class="decision-arrow">↓</div><div class="decision-node"><b>Focal vs. difuso</b><span>Motor, ocular, respiratorio</span></div><div class="decision-arrow">↓</div><div class="decision-node"><b>TC/laboratorio/toxicología</b><span>Según hipótesis</span></div><div class="decision-arrow">↓</div><div class="decision-node"><b>Tratar etiología</b><span>Estructural · metabólica · tóxica · infecciosa · epiléptica</span></div></div></section>

<section class="lesson-section deep-dive"><div class="lesson-number">11.18</div><h2>Conciencia = vigilia + contenido</h2><p>El nivel de conciencia depende de la integridad del sistema reticular activador ascendente del tronco y de ambos hemisferios. Una lesión focal pequeña puede causar coma si compromete estructuras estratégicas del tronco; una lesión hemisférica unilateral aislada suele requerir efecto de masa o herniación para deprimir profundamente la conciencia.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">11.19</div><h2>Herniación uncal y III par</h2><p>El desplazamiento medial del lóbulo temporal puede comprimir el III par, inicialmente sobre fibras parasimpáticas superficiales. Esto produce midriasis ipsilateral y pérdida de reactividad. A medida que progresa la herniación, se comprometen pedúnculos cerebrales y tronco, apareciendo deterioro motor y respiratorio.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">11.20</div><h2>Decorticación vs. descerebración</h2><p>La flexión anormal de miembros superiores con extensión de inferiores sugiere lesión por encima del núcleo rojo; la extensión de extremidades puede reflejar daño más caudal del tronco. Estas posturas son patrones de respuesta motora, no diagnósticos etiológicos.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">11.21</div><h2>Reflejo oculocefálico</h2><p>Con columna cervical segura, la rotación de la cabeza provoca desviación conjugada de ojos en dirección opuesta si los circuitos troncoencefálicos están íntegros. La ausencia de respuesta en un paciente no sedado aporta información sobre integridad del tronco.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">11.22</div><h2>Reflejo oculovestibular</h2><p>La irrigación con agua fría del conducto auditivo genera una respuesta ocular predecible en el paciente comatoso con tronco intacto. Esta prueba evalúa conexiones vestibulares, fascículo longitudinal medial y núcleos oculomotores.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">11.23</div><h2>Coma metabólico: simetría y preservación pupilar relativa</h2><p>Las encefalopatías metabólicas afectan de manera difusa el cerebro y suelen producir hallazgos simétricos. Las pupilas pueden conservar reactividad hasta fases avanzadas, a diferencia de muchas lesiones estructurales de tronco. Esta regla orienta, pero no es absoluta.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">11.24</div><h2>Hiponatremia y edema cerebral</h2><p>Cuando el sodio extracelular cae rápidamente, el gradiente osmótico favorece entrada de agua a las células cerebrales. El edema puede producir cefalea, vómitos, crisis y coma. La velocidad de corrección también importa porque una corrección excesivamente rápida en hiponatremia crónica puede lesionar mielina.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">11.25</div><h2>Estado epiléptico no convulsivo en el paciente comatoso</h2><p>Después de una crisis convulsiva, la persistencia de coma no debe atribuirse automáticamente a estado postictal. Movimientos oculares sutiles, mioclonías faciales o fluctuaciones pueden representar actividad ictal persistente. El EEG es decisivo.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">11.26</div><h2>Coma tóxico: toxidromos que localizan el mecanismo</h2><p>Miosis y depresión respiratoria orientan a opioides; midriasis, sequedad y taquicardia pueden aparecer en síndromes anticolinérgicos; sedantes producen depresión difusa. El examen de piel, temperatura, pupilas, respiración y ECG puede revelar el tóxico antes del laboratorio.</p></section>

<section class="lesson-section mastery"><div class="lesson-number">FIJA</div><h2>BADBEAR.MED FIJA</h2><div class="gold-list-pro"><p><b>01.</b> Primero ABC y glucemia.</p><p><b>02.</b> Glasgow no sustituye examen neurológico.</p><p><b>03.</b> Pupilas y motilidad ocular localizan tronco/herniación.</p><p><b>04.</b> Focalidad favorece causa estructural.</p><p><b>05.</b> Hipoglucemia es causa reversible que debe corregirse de inmediato.</p><p><b>06.</b> Sodio y osmolaridad pueden producir edema o contracción cerebral.</p><p><b>07.</b> Miosis + depresión respiratoria orienta a opioides.</p></div></section>`;
})();