(() => {
"use strict";
window.BADBEAR_NEURO_CONTENIDOS=window.BADBEAR_NEURO_CONTENIDOS||{};
window.BADBEAR_NEURO_CONTENIDOS["ela"]=`
<section class="lesson-intro deep-intro"><span class="lesson-label">UNIDAD 14 · ELA</span><h2>Esclerosis lateral amiotrófica: coexistencia de primera y segunda motoneurona</h2><p>Desarrollo basado en <strong>“14. ELA.pdf”</strong>. El material aborda fisiopatología, genética, formas esporádicas/familiares, fenotipos espinal y bulbar, signos de alarma, diagnóstico neurofisiológico, diferenciales, tratamiento y seguimiento funcional.</p></section>
<section class="lesson-section"><div class="lesson-number">14.1</div><h2>Concepto anatomopatológico</h2><p>ELA combina degeneración de <strong>motoneurona superior</strong> —tractos corticoespinales— y <strong>motoneurona inferior</strong> —asta anterior y núcleos motores bulbares—. Esa coexistencia explica el aparente contraste de espasticidad/hiperreflexia con atrofia/fasciculaciones.</p></section>
<section class="lesson-section"><div class="lesson-number">14.2</div><h2>Fisiopatología</h2><p>El PDF reúne excitotoxicidad por glutamato, estrés oxidativo, disfunción mitocondrial, alteraciones estructurales y genética. No existe un único mecanismo suficiente para explicar todos los casos.</p></section>
<section class="lesson-section"><div class="lesson-number">14.3</div><h2>Genética</h2><p>El material menciona SOD1, TDP-43, FUS/TLS y ATX2, y separa formas esporádicas predominantes de formas familiares. La genética adquiere especial relevancia en presentación familiar o juvenil.</p></section>
<section class="lesson-section"><div class="lesson-number">14.4</div><h2>Inicio espinal</h2><p>El fenotipo espinal predomina en el material: debilidad asimétrica, muchas veces distal, con amiotrofia y fasciculaciones, sin dolor radicular ni déficit sensitivo como rasgos centrales.</p></section>
<section class="lesson-section"><div class="lesson-number">14.5</div><h2>Inicio bulbar</h2><p>Disartria, disfagia y sialorrea marcan compromiso bulbar. El PDF señala peor pronóstico del fenotipo bulbar en comparación con el espinal.</p></section>
<section class="lesson-section"><div class="lesson-number">14.6</div><h2>Signos de primera motoneurona</h2><p>Hiperreflexia, espasticidad, respuesta plantar extensora y pérdida de destreza por compromiso corticoespinal orientan a neurona motora superior.</p></section>
<section class="lesson-section"><div class="lesson-number">14.7</div><h2>Signos de segunda motoneurona</h2><p>Atrofia, fasciculaciones, debilidad flácida y pérdida de unidades motoras reflejan compromiso de asta anterior o núcleos motores.</p><div class="bb-fija-neuro"><b>BADBEAR.MED FIJA:</b> ELA se vuelve reconocible cuando aparecen <strong>signos de 1MN + 2MN sin explicación sensitiva equivalente</strong>.</div></section>
<section class="lesson-section"><div class="lesson-number">14.8</div><h2>Fenotipos relacionados</h2><p>El PDF menciona atrofia muscular progresiva cuando predomina 2MN, esclerosis lateral primaria cuando predomina 1MN y formas bulbares progresivas. Estos fenotipos muestran que las enfermedades de motoneurona forman un espectro.</p></section>
<section class="lesson-section"><div class="lesson-number">14.9</div><h2>Hallazgos que hacen dudar de ELA</h2><p>Dolor neuropático o radicular prominente, déficit sensitivo, trastorno esfinteriano, oftalmoplejía/ptosis, ataxia, signos extrapiramidales y evolución en brotes obligan a reconsiderar el diagnóstico.</p></section>
<section class="lesson-section"><div class="lesson-number">14.10</div><h2>ELA y deterioro frontotemporal</h2><p>El material reconoce asociación con alteraciones cognitivas y conductuales frontotemporales. Esto desmonta la idea histórica de que la cognición está siempre intacta.</p></section>
<section class="lesson-section"><div class="lesson-number">14.11</div><h2>Electromiografía</h2><p>La EMG busca evidencia de denervación activa y crónica en múltiples regiones. Su papel es demostrar compromiso de motoneurona inferior más allá de lo clínicamente evidente y apoyar la distribución anatómica.</p></section>
<section class="lesson-section"><div class="lesson-number">14.12</div><h2>Conducción nerviosa</h2><p>Se utiliza para excluir neuropatías motoras y otros mimetizadores. La preservación sensitiva es especialmente importante cuando la clínica sugiere enfermedad de motoneurona.</p></section>
<section class="lesson-section"><div class="lesson-number">14.13</div><h2>RM y estudios de laboratorio</h2><p>La neuroimagen busca compresión cervical, mielopatía, lesiones estructurales u otras causas tratables. El material incluye evaluación renal, hepática, tiroidea y otros estudios para descartar mimetizadores.</p></section>
<section class="lesson-section"><div class="lesson-number">14.14</div><h2>Tratamiento multidisciplinario</h2><p>El PDF enfatiza nutrición, función respiratoria, gastrostomía cuando corresponde, soporte ventilatorio, fisioterapia, comunicación, manejo de secreciones y coordinación multidisciplinaria.</p></section>
<section class="lesson-section"><div class="lesson-number">14.15</div><h2>Tratamiento modificador y seguimiento</h2><p>El material incluye riluzol y seguimiento con ALSFRS-R. El objetivo terapéutico no es solo supervivencia: mantener autonomía, ventilación, nutrición, comunicación y confort.</p></section>
<section class="lesson-section"><div class="lesson-number">14.16</div><h2>Algoritmo</h2><div class="decision-tree"><div class="decision-node primary"><b>Debilidad progresiva</b><span>¿Hay 1MN, 2MN o ambas?</span></div><div class="decision-arrow">↓</div><div class="decision-node"><b>¿Sensibilidad?</b><span>Si es prominente, reconsiderar ELA</span></div><div class="decision-arrow">↓</div><div class="decision-node"><b>EMG/NCV</b><span>Denervación + excluir neuropatía</span></div><div class="decision-arrow">↓</div><div class="decision-node"><b>RM/labs</b><span>Excluir causas tratables</span></div><div class="decision-arrow">↓</div><div class="decision-node"><b>Manejo multidisciplinario</b><span>Respiratorio + nutricional + funcional</span></div></div></section>

<section class="lesson-section deep-dive"><div class="lesson-number">14.17</div><h2>Por qué conviven hiperreflexia y atrofia</h2><p>La lesión corticoespinal elimina modulación inhibitoria sobre circuitos espinales y produce hiperreflexia/espasticidad; simultáneamente, la pérdida de motoneuronas del asta anterior denerva músculo y produce atrofia/fasciculaciones. ELA reúne ambos niveles en un mismo paciente.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">14.18</div><h2>Denervación y reinervación colateral</h2><p>Cuando muere una motoneurona, fibras vecinas pueden emitir brotes colaterales y reinervar fibras huérfanas. Esto crea unidades motoras más grandes. La EMG detecta potenciales de gran amplitud/duración y signos de denervación activa, reflejando simultáneamente pérdida y compensación.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">14.19</div><h2>Fasciculación: qué representa</h2><p>Una fasciculación es contracción visible de una unidad motora por descarga espontánea. En una persona sana puede ser benigna, pero asociada a debilidad progresiva, atrofia y signos de denervación adquiere significado diferente.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">14.20</div><h2>Bulbar vs. pseudobulbar</h2><p>La debilidad bulbar por motoneurona inferior produce atrofia y fasciculaciones linguales, voz nasal y disfagia; el síndrome pseudobulbar por vías corticobulbares puede producir espasticidad, reflejo mandibular aumentado y labilidad emocional. En ELA pueden coexistir.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">14.21</div><h2>Respiración: el pronóstico se decide también fuera de las extremidades</h2><p>La debilidad diafragmática puede manifestarse con ortopnea, sueño no reparador, cefalea matutina y somnolencia antes de la disnea franca. Medidas seriadas de función respiratoria son esenciales para anticipar ventilación no invasiva.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">14.22</div><h2>Nutrición y disfagia</h2><p>El balance energético puede deteriorarse por disfagia, fatiga al comer y mayor gasto. La gastrostomía no es simplemente un procedimiento nutricional: debe planificarse considerando función respiratoria y preferencias del paciente.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">14.23</div><h2>Mimetizadores tratables</h2><p>Mielopatía cervical, neuropatía motora multifocal, miastenia, miopatías y trastornos metabólicos pueden parecer ELA. La presencia de bloqueo de conducción motor, dolor radicular o déficit sensitivo puede redirigir hacia diagnósticos potencialmente tratables.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">14.24</div><h2>ELA y espectro frontotemporal</h2><p>Alteraciones ejecutivas, apatía, desinhibición o cambios de lenguaje pueden acompañar enfermedad motoneuronal. El eje ELA-DFT es biológicamente coherente con proteínas como TDP-43 y obliga a evaluar conducta y toma de decisiones, no solo fuerza.</p></section>
<section class="lesson-section deep-dive"><div class="lesson-number">14.25</div><h2>Seguimiento funcional</h2><p>ALSFRS-R permite cuantificar habla, salivación, deglución, escritura, actividades, marcha y respiración. La tendencia a lo largo del tiempo es más informativa que una medición aislada y ayuda a anticipar necesidades de soporte.</p></section>

<section class="lesson-section mastery"><div class="lesson-number">FIJA</div><h2>BADBEAR.MED FIJA</h2><div class="gold-list-pro"><p><b>01.</b> ELA combina signos de 1MN y 2MN.</p><p><b>02.</b> El fenotipo espinal suele ser asimétrico.</p><p><b>03.</b> La forma bulbar se presenta con disartria/disfagia/sialorrea.</p><p><b>04.</b> Déficit sensitivo prominente va contra ELA.</p><p><b>05.</b> EMG demuestra denervación activa y crónica.</p><p><b>06.</b> RM se utiliza para excluir mimetizadores estructurales.</p><p><b>07.</b> Manejo debe ser multidisciplinario y respiratorio-nutricional.</p></div></section>`;
})();