(() => {
  "use strict";
  const app=document.getElementById("fis-tema-app");
  const temas=Array.isArray(window.BADBEAR_FISIO_TEMAS)?window.BADBEAR_FISIO_TEMAS:[];
  const id=new URLSearchParams(location.search).get("t");
  const tema=temas.find(t=>t.id===id)||temas[0];
  if(!app||!tema)return;
  document.title=`${tema.titulo} | Fisiología | BADBEAR.MED`;
  const leidos=new Set(JSON.parse(localStorage.getItem("badbear_fisio_leidos")||"[]"));
  const i=temas.findIndex(t=>t.id===tema.id),ant=temas[(i-1+temas.length)%temas.length],sig=temas[(i+1)%temas.length];
  app.innerHTML=`<div class="tema-breadcrumb"><a href="../index.html">BADBEAR.MED</a><span>›</span><a href="index.html">Fisiología</a><span>›</span><strong>${tema.area}</strong></div><section class="tema-hero"><div class="tema-icon">${tema.icono}</div><div><span>${tema.area.toUpperCase()}</span><h1>${tema.titulo}</h1><p>${tema.descripcion}</p></div></section><div class="tema-layout"><div><section class="tema-card"><h2>Ruta de estudio</h2><ul><li>Variable fisiológica y valores esperados cuando correspondan.</li><li>Mecanismo y regulación.</li><li>Relación entre estructura y función.</li><li>Gráficas, curvas y fórmulas relevantes.</li><li>Integración con otros sistemas.</li><li>Aplicación clínica o experimental.</li><li>Errores frecuentes de interpretación.</li></ul></section><section class="tema-card"><h2>Recursos del tema</h2><p>La página queda preparada para incorporar apuntes amplios, esquemas, gráficas, tablas, ejercicios, preguntas, PDF, videos y audios.</p></section><section class="tema-note"><h3>BADBEAR.MED FIJA:</h3><p>Aquí se concentrarán relaciones causa-efecto, fórmulas, curvas, variables reguladas y cambios fisiológicos que suelen confundirse en examen.</p></section><p class="tema-source">Temario funcional organizado para BADBEAR.MED a partir de contenidos de Fisiología trabajados por sistemas; no se presenta como índice oficial de un único libro.</p></div><aside class="tema-side"><h3>Navegación</h3><a href="tema.html?t=${ant.id}">← ${ant.titulo}</a><a href="index.html#temas">Todos los temas</a><a href="tema.html?t=${sig.id}">${sig.titulo} →</a><a href="modulo.html?m=preguntas">Banco de preguntas</a><a href="modulo.html?m=examenes">Exámenes pasados</a><a href="modulo.html?m=pdf">PDF</a><a href="modulo.html?m=videos">Videos</a><a href="modulo.html?m=audios">Audios</a><button id="tema-complete" class="tema-complete ${leidos.has(tema.id)?"hecho":""}">${leidos.has(tema.id)?"✓ Tema revisado":"Marcar como revisado"}</button></aside></div>`;
  document.getElementById("tema-complete")?.addEventListener("click",e=>{if(leidos.has(tema.id))leidos.delete(tema.id);else leidos.add(tema.id);localStorage.setItem("badbear_fisio_leidos",JSON.stringify([...leidos]));e.currentTarget.classList.toggle("hecho",leidos.has(tema.id));e.currentTarget.textContent=leidos.has(tema.id)?"✓ Tema revisado":"Marcar como revisado"});
})();
